version: '3'

services:
  app:
    build: ./
    container_name: react-learn-landing
    command: yarn start
    ports:
      - '3000:3000'
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - .:/app/dist
